parser: babel-eslint
env:
  browser: true
  node: true
  commonjs: true
  es6: true
extends: ['eslint:recommended', 'plugin:react/recommended', 'plugin:flowtype/recommended']
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - babel
  - react
  - flowtype
rules:
  color-hex-case:
    - upper
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/jsx-uses-react:
    - error
  react/jsx-uses-vars:
    - error
